### ISSUE TITLE
Multiversion R documentation?

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1273]
Only the `stable` version of the R documentation is deployed. It is built and the artifact is uploaded here:
```
      - name: Build docs
        run: bash tools/r_stage.sh -d

      - name: Upload docs
        uses: actions/upload-artifact@v2
        with:
          name: r-docs
          path: R/opendp/docs
```
and it is dropped into the ghpages checkout here:
```
      - name: Download R Docs
        uses: actions/download-artifact@v3
        with:
          name: r-docs
          path: en/stable/api/r
```

Because only the `stable` version is in the docs, we have an absolute URL instead of a relative link:
```
.. toctree::
   :maxdepth: 1

   Python API User Guide <user-guide/index>
   Python API Reference <python/index>
   R API Reference <https://docs.opendp.org/en/stable/api/r>
   Rust API Reference <https://docs.rs/opendp>
```

Not a high priority, but if it's useful to have multiple versions of the Python docs, it might be good to have multiple versions of the R docs as well. This might involve referencing `tools/r_stage.sh -d` inside the Makefile.
