### ISSUE TITLE
`r` job under `build.yml` doesn't seem to download `lib` artifact

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1399]
- Working on #1378

The comments at the top explain (with the addition of `-*` in my local branch):
```
# * Downloads the lib-* and python_bindings artifacts, creates a Python wheel, uploads to the python_wheel artifact
# * Downloads the lib-* and r_bindings artifacts, creates an R package, uploads to the r_package artifact
```

and while I do see the `lib` download for python:

```
      - name: Download libs
        uses: actions/download-artifact@v4
        with:
          pattern: libs-*
          merge-multiple: true
          path: rust/

      - name: Download Python bindings
        uses: actions/download-artifact@v4
        with:
          name: python_bindings
          path: python/src/opendp/
```

I only see one download for R:
```
    steps:
      - name: Checkout repository
      - name: Set up R
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Download R bindings
      - name: Source tar
      - name: Notes
      - name: Upload R package
```
Is the lib download implicit in another step? Have we actually seen a developer without a checkout of opendp install the opendp R package and use it successfully? For python we have the sanity test that can confirm that package install works in a fresh environment -- I don't know that we do anything like that for R.
