### ISSUE TITLE
gitignore Python and R bindings

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1425]
Previously, they were needed, but after Andy's rewrite of the release CI last fall, they shouldn't need to be checked in. At the time we weren't sure if the first step was going to raise more issues, but the dust has settled on that and we should be able to move forward.

For example:
```
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.channel }}
...
      - name: Download Python bindings
        uses: actions/download-artifact@v4
        with:
          name: python_bindings
          path: python/src/opendp/
```
right now, since the bindings are also checked in, the artifact download is redundant, but we'll rely on that going forward.
