### ISSUE TITLE
Adjust trigger for smoke-test CI

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#258]
The trigger for running a smoke-test is `[push, pull-request]`. This runs smoke-test twice. 
I think this will cut things down:
```yaml
on:
    push:
        branches:
          - main
          - release*
    pull_request:
```
